# Credit to https://github.com/openscript/openscript :)
# Credit to https://github.com/BrunnerLivio/brunnerlivio :)

on:
  issue_comment:
    types: [created, edited, deleted]

name: Guestbook

jobs:
  update_guestbook:
    name: Update guestbook
    if: ${{ github.event.issue.title == 'Find your pokémon' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update guestbook from comments
        uses: actions/github-script@v6
        with:
          script: |
            function getJSONP(url, success) {

            var ud = '_' + +new Date,
                script = document.createElement('script'),
                head = document.getElementsByTagName('head')[0] 
                      || document.documentElement;

            window[ud] = function(data) {
                head.removeChild(script);
                success && success(data);
            };

            script.src = url.replace('callback=?', 'callback=' + ud);
            head.appendChild(script);

            }
            function getRandomInt(min, max) {
                min = Math.ceil(min);
                max = Math.floor(max);
                return Math.floor(Math.random() * (max - min + 1)) + min;
            }

            const number = getRandomInt(1, 898);
            const pokemonName = "";
            const pokemonImage = "";

            getJSONP('https://pokeapi.co/api/v2/pokemon/${number}'', function(data){
                console.log(data);
                pokemonName = data.name.charAt(0).toUpperCase() + data.name.slice(1);
                pokemonImage = https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${number}.png;
            }); 

            const query = `query($owner:String!, $name:String!, $issue_number:Int!) {
              repository(owner:$owner, name:$name){
                issue(number:$issue_number) {
                  comments(first:1,orderBy:{direction:DESC, field:UPDATED_AT}) {
                    nodes {
                      author {
                        avatarUrl(size: 24)
                        login
                        url
                      }
                      bodyText
                      updatedAt
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              issue_number: context.issue.number
            }
            const result = await github.graphql(query, variables)
            const renderComments = (comments) => {
              return comments.reduce((prev, curr) => {
                return `<a href="${curr.author.url}"><img width="24" src="${curr.author.avatarUrl}" alt="${curr.author.login}" /> ${curr.author.login}</a> found a wild ${pokemonName}\n <p align="center"> <img  src="${pokemonImage}"/> </p>`;
              }, "");
            };
            const fileSystem = require('fs');
            const readme = fileSystem.readFileSync('README.md', 'utf8');
            fileSystem.writeFileSync('README.md', readme.replace(/(?<=<!-- Guestbook -->.*\n)[\S\s]*?(?=<!-- \/Guestbook -->|$(?![\n]))/gm, renderComments(result.repository.issue.comments.nodes)), 'utf8');
      - name: Push guestbook update
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am ':sparkles: update guestbook'
          git push
