# Credit to https://github.com/openscript/openscript :)
# Credit to https://github.com/BrunnerLivio/brunnerlivio :)

on:
  issue_comment:
    types: [created, edited, deleted]

name: Guestbook

jobs:
  update_guestbook:
    name: Update guestbook
    if: ${{ github.event.issue.title == 'Find your pokémon' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update guestbook from comments
        uses: actions/github-script@v6
        with:
          script: |
          
            function getRandomInt(min, max) {
                min = Math.ceil(min);
                max = Math.floor(max);
                return Math.floor(Math.random() * (max - min + 1)) + min;
            }

            const number = getRandomInt(1, 898);

            const data = await github.request('https://pokeapi.co/api/v2/pokemon/'+number.toString())
            var pokemonName = data.data.name;
            pokemonName = pokemonName[0].toUpperCase() + pokemonName.substring(1);
            const pokemonImage = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/"+number.toString()+".png";

            const query = `query($owner:String!, $name:String!, $issue_number:Int!) {
              repository(owner:$owner, name:$name){
                issue(number:$issue_number) {
                  comments(first:1,orderBy:{direction:DESC, field:UPDATED_AT}) {
                    nodes {
                      author {
                        avatarUrl(size: 24)
                        login
                        url
                      }
                      bodyText
                      updatedAt
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              issue_number: context.issue.number
            }
            const result = await github.graphql(query, variables)
            const renderComments = (comments) => {
              return comments.reduce((prev, curr) => {
                const body = `<a href="${curr.author.url}"><img width="24" src="${curr.author.avatarUrl}" alt="${curr.author.login}" /> ${curr.author.login}</a> found a wild <h2> <b> ${pokemonName} </b> </h2> \n <p align="center"> <img  src="${pokemonImage}"/> </p>`;

                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: body
                })

                return body;
              }, "");
            };
            const fileSystem = require('fs');
            const readme = fileSystem.readFileSync('README.md', 'utf8');
            fileSystem.writeFileSync('README.md', readme.replace(/(?<=<!-- Guestbook -->.*\n)[\S\s]*?(?=<!-- \/Guestbook -->|$(?![\n]))/gm, renderComments(result.repository.issue.comments.nodes)), 'utf8');
      - name: Push guestbook update
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am ':sparkles: update guestbook'
          git push
